const plants = [
  {
    id: "1",
    name: "Snake Plant",
    type: "Succulent",
    careLevel: "Easy",
    image: "https://i.ibb.co.com/B5KCDSyw/snake-plant.webp",
    description:
      "Upright sword-like leaves that purify air. Extremely hardy and low-maintenance.",
    watering: "Every 2-3 weeks",
  },
  {
    id: "2",
    name: "Pothos",
    type: "Vine",
    careLevel: "Easy",
    image: "https://i.ibb.co.com/6c4x0067/pothos.webp",
    description:
      "Trailing heart-shaped leaves. Perfect for beginners and hanging baskets.",
    watering: "Every 1-2 weeks",
  },
  {
    id: "3",
    name: "ZZ Plant",
    type: "Foliage",
    careLevel: "Easy",
    image: "https://i.ibb.co.com/8nhsNL3W/zz-plant.webp",
    description: "Glossy dark green leaves. Thrives on neglect and low light.",
    watering: "Every 3-4 weeks",
  },
  {
    id: "4",
    name: "Monstera Deliciosa",
    type: "Tropical",
    careLevel: "Medium",
    image: "https://i.ibb.co.com/1fB2wYLV/monstera-deliciosa.webp",
    description: "Iconic split leaves. Adds a bold tropical vibe to any room.",
    watering: "Every 1-2 weeks",
  },
  {
    id: "5",
    name: "Spider Plant",
    type: "Grass-like",
    careLevel: "Easy",
    image: "https://i.ibb.co.com/RTWdC24D/spider-plant.webp",
    description: "Long arching leaves with baby plantlets. Great air purifier.",
    watering: "Every 1 week",
  },
  {
    id: "6",
    name: "Peace Lily",
    type: "Flowering",
    careLevel: "Medium",
    image: "https://i.ibb.co.com/7xCpxw4j/peace-lily.webp",
    description: "Elegant white flowers and glossy leaves. Loves humidity.",
    watering: "Every 1 week",
  },
  {
    id: "7",
    name: "Rubber Plant",
    type: "Tree",
    careLevel: "Medium",
    image: "https://i.ibb.co.com/ttmbZqX/rubber-plant.webp",
    description:
      "Large glossy leaves that can grow tall. Classic indoor statement plant.",
    watering: "Every 1-2 weeks",
  },
  {
    id: "8",
    name: "Aloe Vera",
    type: "Succulent",
    careLevel: "Easy",
    image: "https://i.ibb.co.com/wZFFMCL7/aloe-vera.webp",
    description: "Healing gel inside the leaves. Needs bright light.",
    watering: "Every 2-3 weeks",
  },
  {
    id: "9",
    name: "Fiddle Leaf Fig",
    type: "Tree",
    careLevel: "Hard",
    image: "https://i.ibb.co.com/BVwm6s8d/fiddle-leaf-fig.webp",
    description:
      "Large violin-shaped leaves. Beautiful but needs consistent care.",
    watering: "Every 1-2 weeks",
  },
  {
    id: "10",
    name: "Philodendron Heartleaf",
    type: "Vine",
    careLevel: "Easy",
    image: "https://i.ibb.co.com/xqPZfyQp/philodendron-heartleaf.webp",
    description: "Fast-growing trailing plant with heart-shaped leaves.",
    watering: "Every 1-2 weeks",
  },
  {
    id: "11",
    name: "Calathea Orbifolia",
    type: "Foliage",
    careLevel: "Hard",
    image: "https://i.ibb.co.com/XrDgTC8h/calathea-orbifolia.jpg",
    description: "Stunning striped leaves. Loves high humidity.",
    watering: "Every week",
  },
  {
    id: "12",
    name: "Jade Plant",
    type: "Succulent",
    careLevel: "Medium",
    image: "https://i.ibb.co.com/ds8RVTSw/jade-plant.webp",
    description: "Thick succulent leaves that look like miniature trees.",
    watering: "Every 2-3 weeks",
  },
];

export default plants;
